FROM owncloud/ubuntu:20.04@sha256:5e8521124d714630244d58f080ca5770309b7808b74c7e2aab44f36259a0f29a

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI AsciiDoctor"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/asciidoctor"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/asciidoctor"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/asciidoctor"

ARG BUILD_VERSION
ARG ASCIIDOCTOR_PDF_VERSION

# renovate: datasource=rubygems depName=asciidoctor
ENV ASCIIDOCTOR_VERSION="${BUILD_VERSION:-2.0.17}"
# renovate: datasource=rubygems depName=asciidoctor-pdf
ENV ASCIIDOCTOR_PDF_VERSION="${ASCIIDOCTOR_PDF_VERSION:-1.6.1}"

RUN apt-get update -y && \
  apt-get install -y tree make graphicsmagick-imagemagick-compat graphicsmagick-libmagick-dev-compat ruby ruby-dev zlib1g-dev libxml2-dev bison cmake build-essential libgraphicsmagick1-dev && \
  gem install --no-document "asciidoctor:$ASCIIDOCTOR_VERSION" "asciidoctor-pdf:$ASCIIDOCTOR_PDF_VERSION" rouge coderay pygments.rb concurrent-ruby prawn-gmagick && \
  apt-get purge -y zlib1g-dev libxml2-dev bison cmake && \
  apt-get autoremove -y && \
  apt-get clean -y && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY rootfs /

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["asciidoctor"]
