FROM owncloud/ubuntu:20.04@sha256:09512724b29924f07d224dded8b15fc8529b19a561d96d4bb334db0c0acaa825

LABEL maintainer="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>"
LABEL org.opencontainers.image.title="ownCloud CI AsciiDoctor"
LABEL org.opencontainers.image.url="https://github.com/owncloud-ci/asciidoctor"
LABEL org.opencontainers.image.source="https://github.com/owncloud-ci/asciidoctor"
LABEL org.opencontainers.image.documentation="https://github.com/owncloud-ci/asciidoctor"

ARG BUILD_VERSION
ARG ASCIIDOCTOR_PDF_VERSION

# renovate: datasource=rubygems depName=asciidoctor
ENV ASCIIDOCTOR_VERSION="${BUILD_VERSION:-2.0.15}"
# renovate: datasource=rubygems depName=asciidoctor-pdf
ENV ASCIIDOCTOR_PDF_VERSION="${ASCIIDOCTOR_PDF_VERSION:-1.6.0}"

RUN apt-get update -y && \
  apt-get install -y tree make graphicsmagick-imagemagick-compat graphicsmagick-libmagick-dev-compat ruby ruby-dev zlib1g-dev libxml2-dev bison cmake build-essential && \
  gem install --no-document "asciidoctor:$ASCIIDOCTOR_VERSION" "asciidoctor-pdf:$ASCIIDOCTOR_PDF_VERSION" rouge coderay pygments.rb concurrent-ruby prawn-gmagick && \
  apt-get purge -y ruby-dev zlib1g-dev libxml2-dev bison cmake build-essential && \
  apt-get autoremove -y && \
  apt-get clean -y && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY rootfs /

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["asciidoctor"]
